config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }


  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }


  namespace :admins do
    get 'order_appends/show'
    get 'order_appends/index'
  end


  root 'home#top'
  get 'get_genre' => 'products#get_genre'

  get 'home/success' => 'home/success'
  get 'home/master' => 'home/master'
  get 'home/select' => 'home/select'

  #mail
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  #mail返信
  get 'inquiry/admin_index' => 'inquiry#admin_index'
  get 'inquiry/:id' => 'inquiry#admin_show',as: "admin_show"
  post 'inquiry/admin_thanks' => 'inquiry#admin_thanks'


  #mail返信確認gem(letter_opener_web)用
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  # namespace :admins do
  #   get 'discs/create'
  # end
  # namespace :admins do
  #   get 'labels/create'
  # end
  # namespace :admins do
  #   get 'genres/create'
  # end
  # namespace :admins do
  #   get 'endusers/index'
  # end
  # namespace :admins do
  #   get 'artists/create'
  # end
  # namespace :admins do
  #   get 'order_details/show'
  #   get 'order_details/index'
  # end
  # namespace :admins do
  #   get 'products/show'
  #   get 'products/new'
  #   get 'products/index'
  #   get 'products/edit'
  # end
  # get 'carts/create'
  # get 'carts/update'
  # get 'carts/destroy'
  # get 'carts/show'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'address_menus/create'
  # get 'address_menus/show'
  # get 'address_menus/destroy'
  # get 'home/top'
  # get 'home/success'
  # get 'products/index'
  # get 'products/create'
  # get 'products/update'
  # get 'products/destroy'



  resources :products,   only: [:index, :create, :update, :destroy, :show]do
  	resources :comments,  only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
    resource :carts, only:[:create]
  end
  resources :carts, only:[:destroy]

 resources :home,only:[:top,:success]


resources :end_users,only: [:show,:edit,:update,:destroy] do
 resource :address_menus,only:[:create,:new,:destroy]
 resource :carts,only:[:update,:show]

end
 resources :order_appends, only:[:new, :show, :create, :update]
 resources :order_details, only: [:show]

 # resources :order_appends,only:[:create,:new,:show]

 namespace :admins do
 	resources :products, only: [:show, :new, :edit, :index, :create, :update, :destroy]

	 resources :order_details, only: [:index]

	 resources :artists, only: [:create, :new]

	 resources :end_users, only:[:index,:edit,:show,:destroy]

	 resources :genres, only: [:create,:new]

	 resources :discs, only: [:create]

	 resources :labels, only: [:create,:new]

   resources :order_appends,only:[:show,:index,:update]
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def success
    render :layout => nil
  end


  def master
  	render :layout => nil
  end

  def select
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/master.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TATSUYA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" >

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div class="top-wrapper">
		<div class="master-image">
			<div class="container">
				<div class="top-title">
					<h2 class="sans white">TATSUYA</h2>
				</div>
				<div class="btn-position">
					<div class="sign clearfix">
						<%= link_to '新規登録',new_admin_registration_path,class: "sans white" %>
					</div>
					<div class="sign clearfix">
						<%= link_to 'ログイン',new_admin_session_path,class: "sans white" %>
					</div>
				</div>
			</div>
		</div>
	</div>

    <footer>
      <div class="container">
        <h3>TATSUYA<span style="padding-left: 50px;">長野県長野市長野原1-12-1</span>
          <p class="nav-list-item" style="padding-left: 50px;">
            <% if end_user_signed_in? %>
              <%= link_to "ログアウト", destroy_end_user_session_path,class: "header-title glyphicon glyphicon-log-out logout", method: :delete %>
            <% elsif admin_signed_in? %>
              <%= link_to "ログアウト", destroy_admin_session_path,class: "header-title glyphicon glyphicon-log-out logout", method: :delete %>
            <% else %>
            <% end %>
          </p>
        </h3>

      </div>
    </footer>

  </body>
</html>

app/views/home/select.html.erb
	<div class="select-wrapper">
		<div class="container">
				<div class="select"style="text-align: center; margin:50px ;">
					<div class="sselect clearfix">
						<%= link_to 'レーベル・アーティスト・ジャンル登録に戻る',new_admins_artist_path %>
					</div>
					<div class="select clearfix">
						<%= link_to '商品登録画面へ進む',new_admins_product_path %>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/home/success.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TATSUYA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.0/css/all.css" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
	<div class="success">
         <div class="success-text">
      	   <h1><img src="/success.jpeg" alt="写真" width="96" height="65">ご購入ありがとうございます<img src="/success.jpeg" class="flip-horizontal" alt="写真" width="96" height="65"></h1>
           <h4>本店は今年で30週年となります。</h4>
           <h4>そのため、インターネットでの販売に力を入れている次第でございます。</h4>
           <h4>今後も入荷の幅を広げていこうと思いますので、よろしくおねがい致します。</h4>
        </div>
        <div class="success-button">
          <%= link_to "商品一覧に戻る", products_path, class: "btn" %>
        </div>
   </div>
<div><canvas id="myChart"></canvas></div>

<!-- 各ボタン -->
<!-- <div style="text-align:center">
  <button id="randomizeData">ランダムデータ</button>
  <button id="addDataset">データセットの追加</button>
  <button id="removeDataset">データセットの削除</button>
  <button id="addData">データの追加</button>
  <button id="removeData">データの削除</button>
</div>
 -->
<script>
// 色の設定
var colorSet = {
  red: 'rgb(255, 99, 132)',
  orange: 'rgb(255, 159, 64)',
  yellow: 'rgb(255, 205, 86)',
  green: 'rgb(75, 192, 192)',
  blue: 'rgb(54, 162, 235)',
  purple: 'rgb(153, 102, 255)',
  grey: 'rgb(201, 203, 207)'
};

// 乱数生成(0～100)
var rnd100 = function(){
  return Math.round(Math.random() * 100);
};

// 色のRGB変換
var color = Chart.helpers.color;

/*
 * チャートの初期設定
 */
var config = {
  type: 'radar',
  data: {
    labels: ["J-POP", "ROCK", "Hip Hop", "アイドル", "洋楽", "レゲェ", "R&B"],
    datasets: [{
      label: "ジャンル別データ",
      backgroundColor: color(colorSet.blue).alpha(0.5).rgbString(),
      borderColor: colorSet.blue,
      pointBackgroundColor: colorSet.blue,
      data: [ "ジャンル1", "ジャンル2", "ジャンル3", "ジャンル4", "ジャンル5", "ジャンル6", "ジャンル7"]
    },]
  },
  options: {
    animation:false,
    showTooltips: false,
    legend: { position: 'bottom' },
    title: {
      display: true,
      fontSize:20,
      fontColor:'#666',
      text: 'one week chart!'
    },
    scale: {
      display: true,
      pointLabels: {
        fontSize: 15,
        fontColor: colorSet.yellow
      },
      ticks: {
        display: true,
        fontSize: 12,
        fontColor: colorSet.green,
        min: 0,
        max: 100,
        beginAtZero: true
      },
      gridLines: {
        display: true,
        color: colorSet.yellow
      }
    }
  }
};

/*
 * チャートの作成
 */
var myRadar = new Chart($("#myChart"), config);

/*
 * ランダムデータ（#randomizeData）
 */
// $("#randomizeData").click(function(){
//   config.data.datasets.forEach(function(dataset){
//     dataset.data = dataset.data.map(function(){
//       return rnd100();
//     });
//   });

//   myRadar.update();
// });

// var colorNames = Object.keys(colorSet);

// /*
//  * データセットの追加（#addDataset）
//  */
// $("#addDataset").click(function(){
//   var colorName = colorNames[config.data.datasets.length % colorNames.length];;
//   var newColor = colorSet[colorName];

//   var newDataset = {
//     label: 'Dataset ' + config.data.datasets.length,
//     borderColor: newColor,
//     backgroundColor: color(newColor).alpha(0.2).rgbString(),
//     pointBorderColor: newColor,
//     data: [],
//   };

//   for (var index=0; index < config.data.labels.length; ++index) {
//     newDataset.data.push(rnd100());
//   }

//   config.data.datasets.push(newDataset);
//   myRadar.update();
// });

// /*
//  * データの追加（#addData）
//  */
// $("#addData").click(function(){
//   if (config.data.datasets.length > 0){
//     config.data.labels.push('dataset #' + config.data.labels.length);

//     config.data.datasets.forEach(function(dataset){
//       dataset.data.push(rnd100());
//     });

//     myRadar.update();
//   }
// });

// /*
//  * データセットの削除（#removeDataset）
//  */
// $("#removeDataset").click(function(){
//   config.data.datasets.splice(0, 1);
//   myRadar.update();
// });

// /* 
//  * データの削除（#removeData）
//  */
// $("#removeData").click(function(){
//   config.data.labels.pop(); // remove the label first

//   config.data.datasets.forEach(function(dataset){
//     dataset.data.pop();
//   });

//   myRadar.update();
// });

</script>

















  </body>
</html>

app/views/home/top.html.erb
<div class="top-wrapper">
	<div class="top-image">
		<div class="container">
			<div class="top-title">
				<h2 class="sans white">TATSUYA</h2>
			</div>
			<div class="btn-position">
				<div class="sign clearfix">
					<%= link_to '新規登録',new_end_user_registration_path,class: "sans white" %>
				</div>
				<div class="sign clearfix">
					<%= link_to 'ログイン',new_end_user_session_path,class: "sans white" %>
				</div>
			</div>
		</div>
	</div>
</div>