config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }


  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }


  namespace :admins do
    get 'order_appends/show'
    get 'order_appends/index'
  end


  root 'home#top'
  get 'get_genre' => 'products#get_genre'

  get 'home/success' => 'home/success'
  get 'home/master' => 'home/master'
  get 'home/select' => 'home/select'

  #mail
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  #mail返信
  get 'inquiry/admin_index' => 'inquiry#admin_index'
  get 'inquiry/:id' => 'inquiry#admin_show',as: "admin_show"
  post 'inquiry/admin_thanks' => 'inquiry#admin_thanks'


  #mail返信確認gem(letter_opener_web)用
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  # namespace :admins do
  #   get 'discs/create'
  # end
  # namespace :admins do
  #   get 'labels/create'
  # end
  # namespace :admins do
  #   get 'genres/create'
  # end
  # namespace :admins do
  #   get 'endusers/index'
  # end
  # namespace :admins do
  #   get 'artists/create'
  # end
  # namespace :admins do
  #   get 'order_details/show'
  #   get 'order_details/index'
  # end
  # namespace :admins do
  #   get 'products/show'
  #   get 'products/new'
  #   get 'products/index'
  #   get 'products/edit'
  # end
  # get 'carts/create'
  # get 'carts/update'
  # get 'carts/destroy'
  # get 'carts/show'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'address_menus/create'
  # get 'address_menus/show'
  # get 'address_menus/destroy'
  # get 'home/top'
  # get 'home/success'
  # get 'products/index'
  # get 'products/create'
  # get 'products/update'
  # get 'products/destroy'



  resources :products,   only: [:index, :create, :update, :destroy, :show]do
  	resources :comments,  only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
    resource :carts, only:[:create]
  end
  resources :carts, only:[:destroy]

 resources :home,only:[:top,:success]


resources :end_users,only: [:show,:edit,:update,:destroy] do
 resource :address_menus,only:[:create,:new,:destroy]
 resource :carts,only:[:update,:show]

end
 resources :order_appends, only:[:new, :show, :create, :update]
 resources :order_details, only: [:show]

 # resources :order_appends,only:[:create,:new,:show]

 namespace :admins do
 	resources :products, only: [:show, :new, :edit, :index, :create, :update, :destroy]

	 resources :order_details, only: [:index]

	 resources :artists, only: [:create, :new]

	 resources :end_users, only:[:index,:edit,:show,:destroy]

	 resources :genres, only: [:create,:new]

	 resources :discs, only: [:create]

	 resources :labels, only: [:create,:new]

   resources :order_appends,only:[:show,:index,:update]
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

	belongs_to :product
	belongs_to :end_user, class_name: "EndUser", foreign_key: "enduser_id"

	# validate :cart_quantity_limit

	# def add_product(product_id)
	# 	current_product = products.find_by_product_id(product_id)
	# 	if current_product
	# 		current_product.quantity += 1
	# 	else
	# 		current_product = products.build(product_id: product_id)
	# 	end
	# 	current_product
	# end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def create
    # if @cart
    #   @cart = current_cart.cart.build(product_id: params[:product_id])
    # end

    #　この下　application/controllerに current_cartのメソッド記述あり
    @hoge = Product.find(params[:product_id])
    @cart = current_cart(@hoge)
    @cart.enduser_id = current_end_user.id
    # この下の一文で、足したquantityが反映されている
    @cart.quantity += params[:cart][:quantity].to_i
    if @cart.quantity >= @hoge.stock
       @cart.quantity = @hoge.stock
       flash[:notice] = "購入個数が在庫数を超えたので、限界の数とさせて頂きます"
    end

  	@cart.save
    redirect_to end_user_carts_path(@cart.enduser_id)
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_to end_user_carts_path

  end

  def destroy
  	cart = Cart.find_by(id: params[:id])
    cart.destroy
    redirect_to end_user_carts_path(current_end_user.id)
  end

  def show

  	# if文使って、ユーザー規制する
  	# @cart = Cart.find(params[:id])
  	# カートの中身を全て出すため
  	@carts = Cart.all
    @cart_less = current_end_user.carts
    # 配送料
    @fee = 500
    # 消費税
    @tax = 1.08
    @order_append = OrderAppend.new



     # if @cart.stock != 0
    #  @cart_less.each do |cart|
    #   (1..cart.product.stock).each do |s|
    #     add_limit = [s,s]
    #     @limit.push(add_limit)
    #   end
    # end

end

  private
   def cart_params
   	params.require(:cart).permit(:quantity,:product_id)
   end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<!-- form内のコードを整理する　＝＞　確認ボタンが反応する  もしくはターボリンクス -->


<div class = "cart-index-wrapper">
	<div class ="container">
	 	<div class="row" style="margin-top: 50px;">
	 		<div class="col-xs-12">
		 		<table class="table cart-table">

					<tbody>

					<% current_end_user.carts.each do |cart| %>
						<tr style="padding: 20px 10px;" class="row">
							<td class="col-xs-4">
								<%= attachment_image_tag cart.product,:profile_image,:fill,200,200, fallback: "no_image.jpg", size:"200x200" %>
							</td>
							<td class="col-xs-4">
								<p style="border-bottom:1.0px solid black; font-size: 20px;"><%= cart.product.album_name %>／<%= cart.product.artist.name %></p>
								<br>
							<div>
								<p>数量
									<%	@limit = [] %>
									<% @limit.clear %>
								<%  (1..cart.product.stock).each do |s| %>
                  					<%  add_limit = [s,s] %>
     								<%  @limit.push(add_limit) %>
     							<% end %>

									<%= form_for cart, url: end_user_carts_path(id: cart.id), method: :PUT do |f| %>
										<%= f.select :quantity, @limit, :selected=>cart.quantity %></p>
										<p>単価<%= cart.product.price %></p>
								<%#= cart.select :quantity, [["1",1],["2",2],["3",3],["4",4]] %>
															<!-- 左が見せる値右がデータベースに入れる値 -->
									<%= f.submit "数量変更を反映させる",class: "btn btn-info" %>
									<% end %>
									<%= link_to "削除", cart_path(cart.id), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn btn-danger" %>
							</div>
							</td>
							<%# @cart.line_items.each do |item| %>
							<%#= (item.good.price).to_i %>
							<%# end %>
							<td class="col-xs-4">
								<%# @subtotal += cart.product.price * cart.quantity %>
								<!-- <p>金額：</p> --><%#= cart.product.price * cart.quantity %>
								<h3>商品価格<%= get_subtotal(cart) %></h3>
								<%#= @subtotal %>
							</td>
						</tr>
					<% end %>
					</tbody>

				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-4 col-xs-offset-8">
				<% if current_end_user.carts.blank? %>
					<h4 style="border:1.0px solid black; text-align: center; margin-top: 200px;">金額</h4>
					<h4 style="border-bottom:1.0px solid black;margin-top: 20px;">配送料/<h4>
					<h4 style="border-bottom:1.0px solid black;margin-top: 20px;">税込価格</h4>

				<% else %>

					<h4 style="border:1.0px solid black; text-align: center; margin-top: 200px;">金額</h4>
					<h4 style="border-bottom:1.0px solid black;margin-top: 50px;">小計/<%= (get_price(@carts) * @tax).floor %></h4>
					<h4 style="border-bottom:1.0px solid black;margin-top: 20px;">配送料/500<h4>
					<h4 style="border-bottom:1.0px solid black;margin-top: 20px;">合計/
					<%  price = get_price(@carts) + @fee %>
					<%= form_for @order_append do |f| %>
						<%= f.hidden_field :subtotal,value: price %>
					<%= (get_price(@carts)* @tax + @fee ).floor %>
					</h4>
					<button style="width: 60%;" class="btn btn-primary"><%= f.submit "購入画面へ",class: "btn btn-primary" %></button>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>