config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }


  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }


  namespace :admins do
    get 'order_appends/show'
    get 'order_appends/index'
  end


  root 'home#top'
  get 'get_genre' => 'products#get_genre'

  get 'home/success' => 'home/success'
  get 'home/master' => 'home/master'
  get 'home/select' => 'home/select'

  #mail
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  #mail返信
  get 'inquiry/admin_index' => 'inquiry#admin_index'
  get 'inquiry/:id' => 'inquiry#admin_show',as: "admin_show"
  post 'inquiry/admin_thanks' => 'inquiry#admin_thanks'


  #mail返信確認gem(letter_opener_web)用
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  # namespace :admins do
  #   get 'discs/create'
  # end
  # namespace :admins do
  #   get 'labels/create'
  # end
  # namespace :admins do
  #   get 'genres/create'
  # end
  # namespace :admins do
  #   get 'endusers/index'
  # end
  # namespace :admins do
  #   get 'artists/create'
  # end
  # namespace :admins do
  #   get 'order_details/show'
  #   get 'order_details/index'
  # end
  # namespace :admins do
  #   get 'products/show'
  #   get 'products/new'
  #   get 'products/index'
  #   get 'products/edit'
  # end
  # get 'carts/create'
  # get 'carts/update'
  # get 'carts/destroy'
  # get 'carts/show'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'address_menus/create'
  # get 'address_menus/show'
  # get 'address_menus/destroy'
  # get 'home/top'
  # get 'home/success'
  # get 'products/index'
  # get 'products/create'
  # get 'products/update'
  # get 'products/destroy'



  resources :products,   only: [:index, :create, :update, :destroy, :show]do
  	resources :comments,  only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
    resource :carts, only:[:create]
  end
  resources :carts, only:[:destroy]

 resources :home,only:[:top,:success]


resources :end_users,only: [:show,:edit,:update,:destroy] do
 resource :address_menus,only:[:create,:new,:destroy]
 resource :carts,only:[:update,:show]

end
 resources :order_appends, only:[:new, :show, :create, :update]
 resources :order_details, only: [:show]

 # resources :order_appends,only:[:create,:new,:show]

 namespace :admins do
 	resources :products, only: [:show, :new, :edit, :index, :create, :update, :destroy]

	 resources :order_details, only: [:index]

	 resources :artists, only: [:create, :new]

	 resources :end_users, only:[:index,:edit,:show,:destroy]

	 resources :genres, only: [:create,:new]

	 resources :discs, only: [:create]

	 resources :labels, only: [:create,:new]

   resources :order_appends,only:[:show,:index,:update]
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord

  # attr_accessor :name, :email, :message
#mail用
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    # admin側の一覧画面で情報を持ってくる為のflag
    @inquiry.mail_flag = 1
      @inquiry.save
    InquiryMailer.received_email(@inquiry).deliver
    # 完了画面を表示
    render :action => 'thanks'

	end


  def admin_index
    #mail_flag:1の情報を持ってくる
  	@inquiry = Inquiry.where(mail_flag: 1)
  end

  def admin_show
  	@inquiries = Inquiry.find(params[:id])
  	@inquiry = Inquiry.new
  end

  def admin_thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
      @inquiry.save
    InquiryMailer.reply_email(@inquiry).deliver
    render :action => 'admin_thanks'
  end


  private

  def inquiry_params
  	params.require(:inquiry).permit(:name, :email, :message )
  end

end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/views/inquiry/admin_index.html.erb
<div class ="inquiry-admin-index">
    <div class="container">
      <div class="row" style="text-align: center;">

      <div class="page-header">
        <h1>お問い合わせ内容一覧</h1>
      </div>

      <% @inquiry.each  do |inquiry| %>
        <table class="table">
          <tr>
            <th>名前</th>
            <td>
              <%= link_to inquiry.name,admin_show_path(inquiry)  %>
            </td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td>
             <%= inquiry.email %>
            </td>
          </tr>
         <tr>
           <th>お問い合わせ日時</th>
            <td>
              <%= inquiry.created_at.strftime('%Y/%m/%d')  %>
           </td>
         </tr>
       </table>
      <% end %>
      <div class="letter_opener">
      <%= link_to "送受信履歴確認", "http://localhost:3000/letter_opener" %>
      </div>
    </div>
  </div>
</div>

app/views/inquiry/admin_show.html.erb
<div class ="inquiry-admin-index">
    <div class="container">
      <div class="row" style="text-align: center;">

      <div class="page-header">
        <h1>お問い合わせ内容詳細</h1>
      </div>
      <div class="row">
            <ol class="inquiry-list" style="border: 2px solid #999;">
              <li class="inquiry-detail">
            <div class="inquiry-body bb">
              <div class="inquiry-text">
                <div class="inquiry-author clearfix">
                              <span class="inquiry-meta">
                                <span class="inquiry-date"><%= @inquiries.created_at.strftime('%Y/%m/%d') %></span>
                                <span class="inquiry-name"><%= @inquiries.name %></span>
                              </span>
                </div>
                <div class="inquiry-entry"><%= @inquiries.message %></div>
              </div>
            </div>
              </li>

           </ol>
      </div>
      <div class="reply">
        <h1>返信用フォーム</h1>
      </div>
    <%= form_for @inquiry, url: inquiry_admin_thanks_path do |f| %>
  <table class="table">
      <tr>
        <th>名前<span class="text-danger"></span></th>
        <td><%= f.text_field :name %></td>
        <%= f.hidden_field :email, value: @inquiries.email %>
      </tr>
      <tr>
        <th>返信内容</th>
       <td><%= f.text_area :message %></td>
      </tr>
   </table>
    <%= f.submit '確認', class: 'btn btn-primary' %>
    <% end %>
    </div>
  </div>
</div>

app/views/inquiry/admin_thanks.html.erb
<div class ="inquiry-thanks">
    <div class="container">
      <div class="row" style="text-align: center;">
		<div class="page-header">
  			<h1>お問い合わせ</h1>
		</div>
			<p>送信完了しました。</p>
		</div>
	</div>
</div>

app/views/inquiry/confirm.html.erb
<div class ="inquiry-confirm">
    <div class="container">
      <div class="row" style="text-align: center;">

      <div class="page-header">
        <h1>お問い合わせ</h1>
      </div>
 
      <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
        <table class="table">
          <tr>
            <th>名前</th>
            <td>
              <%= f.hidden_field :name %>
              <%= @inquiry.name %>
            </td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td>
             <%= f.hidden_field :email %>
             <%= @inquiry.email %>
            </td>
          </tr>
         <tr>
           <th>お問い合わせ内容</th>
            <td>
              <%= f.hidden_field :message %>
              <%= simple_format(@inquiry.message) %>
           </td>
         </tr>
       </table>
       <%= f.submit '送信', :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/inquiry/index.html.erb
<div class ="inquiry-index">
    <div class="container">
      <div class="row" style="text-align: center;">
  <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
    <div class="page-header">
      <h1>お問い合わせ</h1>
    </div>

    <% if @inquiry.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <strong>入力内容にエラーがあります</strong>
        <ul>
          <% @inquiry.errors.each do |attr, msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table class="table">
      <tr>
        <th>名前<span class="text-danger">（必須）</span></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>メールアドレス<span class="text-danger">（必須）</span></th>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <th>お問い合わせ内容</th>
       <td><%= f.text_area :message %></td>
      </tr>
   </table>
    <%= f.submit '確認', class: 'btn btn-primary' %>
  <% end %>
    </div>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class ="inquiry-thanks">
    <div class="container">
      <div class="row" style="text-align: center;">
		<div class="page-header">
  			<h1>お問い合わせ</h1>
		</div>
			<p>お問い合わせいただきありがとうございました。</p>
		</div>
	</div>
</div>