config/routes.rb
Rails.application.routes.draw do


  devise_for :admins,controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }


  devise_for :end_users, controllers: {
    sessions: 'end_users/sessions',
    passwords: 'end_users/passwords',
    registrations: 'end_users/registrations'
  }


  namespace :admins do
    get 'order_appends/show'
    get 'order_appends/index'
  end


  root 'home#top'
  get 'get_genre' => 'products#get_genre'

  get 'home/success' => 'home/success'
  get 'home/master' => 'home/master'
  get 'home/select' => 'home/select'

  #mail
  get 'inquiry' => 'inquiry#index'              # 入力画面
  post 'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post 'inquiry/thanks' => 'inquiry#thanks'     # 送信完了画面
  #mail返信
  get 'inquiry/admin_index' => 'inquiry#admin_index'
  get 'inquiry/:id' => 'inquiry#admin_show',as: "admin_show"
  post 'inquiry/admin_thanks' => 'inquiry#admin_thanks'


  #mail返信確認gem(letter_opener_web)用
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


  # namespace :admins do
  #   get 'discs/create'
  # end
  # namespace :admins do
  #   get 'labels/create'
  # end
  # namespace :admins do
  #   get 'genres/create'
  # end
  # namespace :admins do
  #   get 'endusers/index'
  # end
  # namespace :admins do
  #   get 'artists/create'
  # end
  # namespace :admins do
  #   get 'order_details/show'
  #   get 'order_details/index'
  # end
  # namespace :admins do
  #   get 'products/show'
  #   get 'products/new'
  #   get 'products/index'
  #   get 'products/edit'
  # end
  # get 'carts/create'
  # get 'carts/update'
  # get 'carts/destroy'
  # get 'carts/show'
  # get 'favorites/create'
  # get 'favorites/destroy'
  # get 'comments/create'
  # get 'comments/destroy'
  # get 'address_menus/create'
  # get 'address_menus/show'
  # get 'address_menus/destroy'
  # get 'home/top'
  # get 'home/success'
  # get 'products/index'
  # get 'products/create'
  # get 'products/update'
  # get 'products/destroy'



  resources :products,   only: [:index, :create, :update, :destroy, :show]do
  	resources :comments,  only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
    resource :carts, only:[:create]
  end
  resources :carts, only:[:destroy]

 resources :home,only:[:top,:success]


resources :end_users,only: [:show,:edit,:update,:destroy] do
 resource :address_menus,only:[:create,:new,:destroy]
 resource :carts,only:[:update,:show]

end
 resources :order_appends, only:[:new, :show, :create, :update]
 resources :order_details, only: [:show]

 # resources :order_appends,only:[:create,:new,:show]

 namespace :admins do
 	resources :products, only: [:show, :new, :edit, :index, :create, :update, :destroy]

	 resources :order_details, only: [:index]

	 resources :artists, only: [:create, :new]

	 resources :end_users, only:[:index,:edit,:show,:destroy]

	 resources :genres, only: [:create,:new]

	 resources :discs, only: [:create]

	 resources :labels, only: [:create,:new]

   resources :order_appends,only:[:show,:index,:update]
 end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	# enum記述
	enum status: {
		販売中:1, 停止中:2
	}

	attachment :profile_image

    has_many :carts,dependent: :destroy
    has_many :end_users, through: :carts

	has_many :order_details,dependent: :destroy
	# has_many :order_appends, through: :order_details

	has_many :comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	has_many :discs,dependent: :destroy
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	belongs_to :artist, optional: true
	belongs_to :label, optional: true
	belongs_to :genre, optional: true
	# 親に対し、optional: trueが必要
	#productテーブルリセット


	validates :album_name, {presence: true}
	validates :price, {presence: true}
	validates :body, length: {maximum: 200}
	validates :stock, {presence: true}



	def total_price
		product.price * quantity
	end


	def favorited_by?(enduser)
        	favorites.where(enduser_id: enduser.id).exists?
    end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    # @genre = product.genre
    # @label = product.label
    # @artist = product.artist
  end

  def new
  	@product = Product.new
    @disc = @product.discs.build
    @song = @disc.songs.build
  end

  def create
  	@product = Product.new(params_int(product_params))
  	 if @product.save
        flash[:notice] = "追加しました"
        redirect_to admins_product_path(@product)
     else
        render :new
     end
  end

  def destroy
    @product = Product.find(params[:id])
     if @product.destroy
        flash[:notice] = "削除しました"
        redirect_to admins_products_path
     end
  end

  def index
    @products = Product.all.order(created_at: :desc)
    # @products = Product.page(params[:page]).per(6)

     # 検索オブジェクト
     @search = Product.ransack(params[:q])

    if params[:q]
    # 検索結果
     @products = @search.result
    #ランキング実装用
    end


    @all_ranks = Product.find(Favorite.group(:product_id).order('count(product_id)desc').limit(5).pluck(:product_id))
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
       flash[:notice] = "更新しました"
       redirect_to admins_products_path
    else
       render :edit
    end
  end

  # 文字列が数字だけで構成されていれば true を返す
  def number?(str)
    # 文字列の先頭(\A)から末尾(\z)までが「0」から「9」の文字か
    nil != (str =~ /\A[0-9]+\z/)
  end

  private
	def product_params
		params.require(:product).permit(:artist_id,:label_id,:genre_id,:profile_image,:album_name,:price,:stock,:status,:body,
      :discs_attributes=> [:id, :product_id, :disc_number, :_destroy,
        :songs_attributes=> [:id, :disc_id, :name, :track, :_destroy]])
	end
# ーーーーenum記述ーーーーーーーーー
  def params_int(product_params)
    product_params.each do |key,value|
       if number?(value)
        product_params[key]=value.to_i
       end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

    # 検索オブジェクト
    @search = Product.ransack(params[:q])
    # 検索結果
    #@products = @search.result
  	#ランキング実装用
  	@all_ranks = Product.find(Favorite.group(:product_id).order('count(product_id)desc').limit(10).pluck(:product_id))
    #スクロール

    #@products = Product.page(params[:page]).per(9)
    if params[:q]
      #@search = Product.ransack(params[:q])
      @products = @search.result.page(params[:page]).per(10)
    else
      @products = Product.all.order(created_at: :desc).page(params[:page]).per(10)
    end
  end

  def show
  	@product = Product.find(params[:id])
  	@label = @product.label
  	@genre = @product.genre
    @artist = @product.artist
    @cart = Cart.new

    if @product.stock != 0
      @limit = []
      (1..@product.stock).each do |s|
        add_limit = [s,s]
        @limit.push(add_limit)
      end
    end
    @comment = Comment.new
    if @product.status == 1.to_i
      rdirect_to products_path
    end
  end

  def get_genre
    @product = Product.find(params[:id])
    @genre = @product.genre
  end

  def create
  end


end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="productindex-wrapper" style="color: #888888">
	<div class="container" style="width:100%;">
	  <h1 style="text-align: center;">TATSUYA</h1>
	   <div class="row" style="text-align: center;">

	   	<%= search_form_for @search do |f| %>
	    <!--nameカラムに対して部分一致検索ができる-->
	    	<div class="row text-right" style="padding-right: 3%;">
	    		<%= f.label :album_name_cont, "商品検索" %>
	    		<%= f.text_field :album_name_cont %>
	    		<%= f.submit "検索" %>
	    	</div>
	    <% end %>

	   </div>

	  	 <div clss="row">
	  		<div class="col-xs-2" style="padding-top: 1%; margin-top: 10px;  border-right:3px solid #999;">
	  		  <h3>ランキング</h3>
	  		  <% @all_ranks.each.with_index(1) do |rank,i| %>
	  			<div class="row" style="display: inline-block; text-align: center;margin: 0 auto;padding-left:8%;">
	  				<h4 style="margin-bottom: 0; padding-top: 10px;padding-left: 10%;"><%= i %>位</h4>
	  				<%= link_to product_path(rank) do %>
						<%= attachment_image_tag rank, :profile_image, :fill, 150, 150,format:"jpeg",fallback: "no_image.jpg",size:'150x150' %>
					<% end %>
	  				<p style="margin-bottom: 5px; padding-top: 5px; padding-left: 10%;"><%= rank.artist.name %></p>
					<p style="margin-bottom: 5px;padding-left: 10%;"><%= rank.album_name %></p>
					<p style="margin-bottom: 5px;padding-left: 10%;"><%= rank.price %>円</p>
	  			</div>
	  		  <% end %>
	  		</div>
	  		<div class="offset-1 col-xs-10" style="padding-top: 1%;border-right:3px solid #999;">
	  		  <h3 style="padding-left: 4%; padding-bottom: 10px;background-color: #000080;color: yellow;">CD一覧</h3>
	  			<ul class="product-list">
	  				<!-- ---------------------------------------------------- -->

	  				<ul class="skill-list jscroll">
		  				<% @products.each do |product| %>
						    <li class="product" style="border: 4px solid white; box-shadow: 0 0 5px gray;">
								<div>
									<%= link_to product_path(product) do %>
									<%= attachment_image_tag product, :profile_image, :fill, 200, 200,format:"jpeg",fallback: "no_image.jpg",size:'200x200' ,class: "rounded" %>
									<% end %>
								<div style="padding-left: 7%; padding-bottom: 5%;">
									<p style="margin-bottom: 0px; padding-top: 10px;font-weight: bold;"><%= product.artist.name %></p>
									<p style="margin-bottom: 0px;"><%= product.album_name %></p>
									<p style="margin-bottom: 0px;"><%= product.price %>円</p>
								</div>
								</div>
							</li>
						<% end %>
						<%= paginate @products %>
					</ul>
					<!-- ---------------------------------------------------- -->
				</ul>
	  		</div>
	  	 </div>
	</div>
</div>

app/views/products/show.html.erb
<div class="productshow-wrapper">
	<div class="container">
		<div class="row" style="padding-top: 10px;">
			<div class="col-xs-4" style="padding-top: 3%">
				<p style="border-bottom:3px solid #999;">アルバム名:
				<span style="padding-left: 30px;font-size: 20px"><%= @product.album_name %></span>
				</p>
				<%= attachment_image_tag @product, :profile_image, format: 'jepg', fallback: "no_image.jpg", size: "300x300" %>
				<div style="float: left; padding: 5px;">
						<P style="font-size: 15px;">レーベル名:
							<span style="font-size: 20px; padding-left: 30px;"><%= @product.label.name %></span></P>
						<p style="font-size: 15px;">価格:
							<span style="font-size: 20px; padding-left: 30px;"><%= @product.price %>円</span></p>
						<p style="font-size: 15px;">販売状況:
							<span style="font-size: 20px;padding-left: 30px;"><%= @product.status %></span></p>
						<p style="font-size: 15px;">在庫数:
							<span style="font-size: 20px; padding-left: 30px;"><%= @product.stock %></span><p>

					<%= form_for [@product, @cart], url: product_carts_path(@product) do |f| %>
						<!-- <span style="font-size: 15px;">個数:</span> --><%#= f.number_field :quantity %>
					<% if @product.stock > 0 %>
						<p style="font-size: 15px;">個数:
						<span style="font-size: 15px; padding-left: 30px;"><%= f.select :quantity, @limit %></span></p>
					<% end %>

						<%= f.hidden_field :product_id, value: @product.id %>
						<div class="row" style="padding: 10px">
							<% if end_user_signed_in? %>
					        <% if @product.favorited_by?(current_end_user) %>
				  				<li class="favorite">
				    				<%= link_to product_favorites_path(@product), method: :delete do %>
				      				    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
				      				<%= @product.favorites.count %>
									<% end %>
							<% else %>
				    				<%= link_to product_favorites_path(@product), method: :post do %>
				      					<i class="far fa-heart" aria-hidden="true"></i>
				      					<%= @product.favorites.count %> いいね
				    				<% end %>
						    <% end %>
						   <% else %>
				      					<i class="far fa-heart" aria-hidden="true"></i>
				      					<%= @product.favorites.count %> いいね
				    		<% end %>
						</div>
							<% if end_user_signed_in? %>
						<% if @product.status == "販売中" && @product.stock > 0 %>
				      		<%= f.submit "カートに追加する", class: "btn btn-default" %>
				      	<% else%>
				      		<p style="font-size: 25px;color: red">現在購入できません</p>
			      		<% end %>
			      			<% end %>
				    <% end %>
				</div>
			</div>
			<div class="col-xs-8" style="padding-left: 10%;padding-top: 4%;">
			  	<table class="product-main" style="font-size: 16px;">
			  		<thead>
			  			<tr>
			  				<th></th>
			  				<th>曲名</th>
			  				<th>アーティスト</th>
			  			</tr>
			  		</thead>
			  		<% @product.discs.each do |disc| %>
				  		<% disc.songs.each do |song| %>
					  		<tbody>
					  			<tr>
					  				<td width="15%"><%= song.track %></td>
					  				<td width="50%"><%= song.name %></td>
					  				<td width="25%"><%= @product.artist.name %></td>
					  			</tr>
					  		</tbody>
			  		    <% end%>
			  		<% end %>
			  	</table>
				<div class="product-comment" style="padding-top: 50%;">
			  		  <p style="border: 1px solid #dddddd; width: 550px; height: 150px"><%= @product.body %></p>
				</div>
			</div>
		</div>
	</div>
</div>
<% if end_user_signed_in? %>
<div class="add-review-wrapper" style="padding-top: 20px;">
	<div class="container" style="border: 3px solid #dddddd; border-radius: 10px; height: auto;">
		<h2>レビュー追加</h2>
		<%= form_for [@product, @comment] do |f| %>
			<div class="row">
				<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
				<div class="add-review" style="padding: 10px;">
					<%= f.submit "送信する", class: "btn1 btn-lg btn-base-1 mt-20 pull-right" %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<% end %>

<div class="review-wrapper">
	<div class="container">
  		<h2>レビュー一覧</h2>
  		<div class="row"  style="border: 2px solid #999;">
  			<% @product.comments.each do |comment| %>
  		  		<ol class="review-list">
	        		<li class="comment">
						<div class="comment-body bb">
							<div class="comment-text">
								<div class="comment-author clearfix">
		                        	<span class="comment-meta">
		                          	<span class="comment-date"><%= comment.created_at.strftime('%Y/%m/%d') %></span>
		                          	<span class="comment-date"><%= comment.end_user.first_name %>さんのレビュー</span>
		                        	</span>
								</div>
								<div class="comment-entry"><%= comment.comment %></div>
							</div>
						</div>
	          		</li>
					<% if current_end_user.id == comment.enduser_id %>
						<div class="text-right">
							<p>
								<%= link_to "削除", product_comment_path(@product,comment), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn1 btn-lg btn-base-1 mt-10" %>
							</p>
						</div>
					<% end %>
         		</ol>
  	 		<% end %>
  	 	</div>
	</div>
</div>